apiVersion: v1
kind: Namespace
metadata:
  name: replace-me
  labels:
    app.kubernetes.io/part-of: replace-me
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
