apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
  labels:
    app.kubernetes.io/part-of: clickhouse-on-aks
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
