apiVersion: v1
kind: Namespace
metadata:
  name: superset
  labels:
    app.kubernetes.io/part-of: apache-superset-on-aks
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
