apiVersion: v1
kind: Namespace
metadata:
  name: flink
  labels:
    app.kubernetes.io/name: apache-flink
    workload: apache-flink
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
