apiVersion: v1
kind: Namespace
metadata:
  name: opensearch
  labels:
    app.kubernetes.io/part-of: opensearch-on-aks
    # OpenSearch's Helm chart optionally runs a privileged sysctl init container.
    # We disable that init container in the blueprint values, so `baseline`
    # enforcement is safe. If you re-enable sysctlInit, relax this to
    # `privileged` or remove the label.
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
