apiVersion: v1
kind: Namespace
metadata:
  name: trino
  labels:
    app.kubernetes.io/part-of: trino-on-aks
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
