apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    app.kubernetes.io/part-of: apache-airflow-on-aks
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
