clusterName: "opensearch"
nodeGroup: "manager"
masterService: "opensearch-manager"

roles:
  - master

replicas: 3

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-credentials
        key: password

opensearchJavaOpts: "-Xms1g -Xmx1g"

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

persistence:
  enabled: true
  storageClass: "managed-csi-premium"
  size: 16Gi

antiAffinityTopologyKey: "kubernetes.io/hostname"
antiAffinity: "hard"

nodeSelector:
  agentpool: osmgr

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "opensearch-manager"
    effect: "NoSchedule"

sysctlInit:
  enabled: true

service:
  type: ClusterIP
  annotations: {}

maxUnavailable: 1
